spring:
  datasource:
    url: jdbc:mysql://localhost:3306/timeline
    username: root
    password: LAIqian~~666
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8080
mybatis:
  configuration:
    use-column-label: true
    use-generated-keys: true
    map-underscore-to-camel-case: true
logging:
  level:
    com.rhenium.timelinebackend.mapper: debug